Controllers/IndexController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace WbtGuardService.Controllers;
public class IndexController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
    [HttpPost]
    public IActionResult SetLanguage(string culture, string returnUrl)
    {
        Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
        );

        return LocalRedirect(returnUrl);
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System.Diagnostics;

namespace WbtGuardService.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WbtGuardService.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WbtGuardService.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Wbt Guard Service";
}
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<div class="text-center">
    <h1 class="display-4">@Localizer["Daemon List"]</h1>
    <div id="services">
        <table class="table table-bordered">
            @*<caption>WbtGuardService 1.0</caption>*@
            <thead>
                <tr>
                    <th>@Localizer["State"]</th>
                    <th>@Localizer["Desc"]</th>
                    <th>@Localizer["Application"]</th>
                    <th>@Localizer["Control"]</th>
                </tr>
            </thead>
            <tbody id="svrlist">

            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="log" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="logContent">
               
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>                
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script lang="javascript">
        var myModal = new bootstrap.Modal(document.getElementById('log'), {
                keyboard: true
            })
        var tt = setInterval(execStatus,1000);
        function execStatus(){
            exec(null, 'Status').then(res=>{})
        }

        async function  exec(processName, command)
        {
            await connection.invoke(command, processName);
            
        }
        const connection = new signalR.HubConnectionBuilder()
            .withUrl("/monitor")
            .withAutomaticReconnect({
                nextRetryDelayInMilliseconds: retryContext => {
                    return Math.random() * 10000;
                }
            })
            .configureLogging(signalR.LogLevel.Information)
            .build();

        async function start() {
            try {
                await connection.start();
                console.log("SignalR Connected.");

                var li = '<tr id="$id"><td class="state">$satte</td><td class="desc">$desc</td><td class="id">$id</td><td class="action">'+
                    '<a onclick="exec(\'$id\',\'Restart\')" href="javascript:void(0);">@Localizer["Restart"]</a>' +
                    '<a onclick="exec(\'$id\',\'Start\')" href="javascript:void(0);">@Localizer["Start"]</a>' +
                    '<a onclick="exec(\'$id\',\'Stop\')" href="javascript:void(0);">@Localizer["Stop"]</a>' +
                    '<a onclick="exec(\'$id\',\'ClearLogs\')" href="javascript:void(0);">@Localizer["Clear Logs"]</a>' +
                    '<a onclick="exec(\'$id\',\'LastLogs\')" href="javascript:void(0);">@Localizer["Logs"]</a>' +
                    '</td></tr>'

                try{
                    var services  = await connection.invoke("GetServices");
                    console.log(services);
                    if(services){
                        $("#svrlist").html();
                        for(var i=0;i< services.length;i++){
                                var s = li.replace(/\$id/g, services[i])
                                .replace(/\$satte/g, '@Localizer["Unknown"]')
                                .replace(/\$desc/g, '@Localizer["Unknown"]');
                                $("#svrlist").append(s)
                        }
                    }
                    await connection.invoke("Status",null);
                }
                catch(e){
                    console.log(e);
                }
                            
            } catch (err) {
                console.log(err);
                setTimeout(start, 5000);
            }
        };

        connection.on("Status",msg =>{
            if(msg && msg.command){
                if(msg.command=='Status'){
                    var id = msg.processName;
                    var parent = $(document.getElementById(id));
                    parent.children('.state').text(msg.status.status);
                    if(msg.status.pid && msg.status.upTime){
                        parent.children('.desc').text('[' + msg.status.pid  + '],@Localizer["Uptime:"]' + msg.status.upTime);
                    }
                    else if (msg.status.pid) {
                        parent.children('.desc').text('[' + msg.status.pid + '],@Localizer["Uptime:"]');
                    }
                    else{
                        parent.children('.desc').text('');
                    }                    
                }
                else{
                    var id = msg.processName;
                    if(msg.status){
                        var parent = $(document.getElementById(id));
                        parent.children('.state').text(msg.status.status);
                    }
                }
            }
            //console.log('status',msg)
        });
        connection.on("LastLogs", msg => {
            if (msg && msg.command) {
                if (msg.command == 'LastLogs') {
                    var id = msg.processName;
                    $('#staticBackdropLabel').text('@Localizer["App"] ' + id);
                    $('#logContent').text(msg.content)
                    myModal.show();

                }
            }            
        });
        connection.onclose(async () => {
            await start();
        });

        // Start the connection.
        start();
    </script>
}

Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ancn.WbtGuardService</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/signalr/signalr.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WbtGuardService.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Wbt Guard Service</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">@Localizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">@Localizer["Privacy"]</a>
                        </li>
                    </ul>
                    <div class="col-md-6 text-right">
                        @await Html.PartialAsync("_SelectLanguagePartial")
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Wbt Guard Service - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Index"
          asp-action="SetLanguage" asp-route-returnUrl="@returnUrl"
          method="post" class="form-horizontal" role="form">
        <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label> <select name="culture"
                                                                                                               onchange="this.form.submit();"
                                                                                                               asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
        </select>
    </form>
</div>